### PR TITLE
Added field for protocol, https or http

### PR DESCRIPTION
**Pull request by stefanoberli**
This makes the extension able to send newsletters in both http and https environments. It would be great if this extension would support https environments out of the box!

### CODE REVIEW

**Comment by PowerKiKi** [comment]
I think it would be best to use the existing domain configuration field instead of adding a new one. So the user can directly enter `https://mydomain.com` instead of splitting the info in two. What do you think ?

**Comment by stefanoberli** [comment]
Hi Adrien

Thanks for your response.
We had the domain configuration field already set to https, but the
internal curl command was hardcoded to http.
This is the main reason why we added the field.
I guess this is more a misconfiguration of the server, than a issue with
the newsletter extension.
So if the extension works with https, I guess you can ignore my pull
request.

Greetings,
Stefan Oberli

**Comment by PowerKiKi** [comment]
Oh, I see I didn't explain myself well. What I mean is the extension currently cannot work with HTTPS. But in order to make it work, I think it would be best to modify the extension to allow to specify protocol directly in the domain field. So to have another PR to modify that. Would this new approach work for your use-case ?

**Comment by stefanoberli** [comment]
Ah now I understand. As a matter of fact, that is exactly how we
implemented it first.
However, that caused an issue where the images were linked with https://
https://my-domain-name (2x https prefix).
So the image links could not be resolved correctly (but the email was sent,
and curl worked).
It would be neccessary to do multiple string replacements to remove the
additional https (there are other occurences beside the images).

In the end we decided to use the approach with the additional field because
it is a smaller change to the code, and easier to implement.

**Comment by PowerKiKi** [comment]
I agree with you it would be slightly more complex, but probably better for end-user. So i think it worth doing it. From what I saw there would be only two places to be careful about the doubled protocol. That should be manageable.

Anyway I'll have a look and see what i can do about it

**Pull request closed without merging**
