### PR TITLE
Issue Updating: Refactorisation of extension updating

### PR DESCRIPTION
**Pull request by marvin-martian**
The next one: As I explained before I had a mechanism for doing extension updates from another extension I was working on. The reason why I added this was because in my previous pull-request I used the signal-slot to to do the automatic update, and I added my update method to Tools which wasn't wanted.

As I had the code out of the bag I thought this project would benefit from it.
The idea is the extension coder, when creating updates, only has to focus on the actual update and not worry about processing forms. Another feature of this updating mechanism is that it should inform the user when an update fails. And when an update fails any committed data is rolled back leaving the users data intact to a pre-update state. It also keeps track of updates and will notify the user if an update has already been executed and when. Also automatic update tasks are only run once. The update history is written in the localConf for the extension.

The general procedure to adding a update task is :
1) Write your update task method. Your method should: make your data changes in a transaction, return a result object from that transaction/s.
2) Register your update task and method with the Update class, set whether the update task is manual, automatic or both.
3) Forget about it.

The reason why I wrote this is so many times I have had extension updates fail, but do not clean up their mess when they do fail. The idea is to change the mentality by making extension coders more conscientious about updates and what happens when things fail. It is not entirely complete, I have not written file transactions yet. Normally my updates are DB so haven't needed to write it yet.

Eventually I would like to get something like this in extbase.

BTW my french translations are babelfish horrible, feel free to make them french. lol :-)

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Landed as https://github.com/Ecodev/newsletter/commit/7b162a0d423af84702a3d2465613b7e7cb6f34a7, but in a very simplified version.

I don't think it's a good idea to store updates history on file system when the update actually concerns the DB. Anyway it's not a feature that is required for Newsletter, because we can always detect whether the updates happened by looking at the actual data.

**Comment by marvin-martian** [comment]
By storing the update history it stops the need to unnecessarily examine the database every time you perform a version update. If you start having many changes over time to the DB in the lifetime of the extension it will speed up the update installation by not running unnecessary queries. But easy... Just using transactions is a massive step forward for friendlier extensions.

i agree with you about saving the update history to conf file but typo3 does not have a specific facility to track extension updates. i could have log it but logs can be cleared, and you would have to search for them. Or I could have written a temp file but temp can also be cleared. Easy extension rollbacks is something that Typo3 lacks.

anyway i will try to submit my next pull requests soonish... More to come.

**Comment by PowerKiKi** [comment]
Agree with you on the update mechanism. We'll see how Newsletter evolves, and if performance really takes a hit later, we'll re-evaluate the situation.

As for future PR, please wait till I release a 2.6.0 (end of week I guess). I am still merging other things from you, most notably the massive PR #71.

**Comment by marvin-martian** [comment]
you asked me to split #71 into multiple pull requests? You still want this?

**Comment by PowerKiKi** [comment]
I did asked you, but it's not necessary anymore. I am doing it myself. So you don't have to do anything until 2.6.0 is out.

**Comment by mbrodala** [comment]
How is one supposed to trigger these updates on update? Notice that we are using Composer mode, thus there is no manual invocation of the EM or similar.

I'm asking in particular because of the `auth_code` field which was added on upgrade to version 3.x and is initially empty causing the `UNIQUE` index to fail. I manually had to deactivate and reactivate the extension to trigger the updates which of course is far from perfect given continuous deployments.

**Comment by PowerKiKi** [comment]
It will appear as usual in Extension Manager if needed:
image

For more detail, see 8bec7751dcb8c7c3decb12e57ab8e17fa7b4cf97.

**Comment by mbrodala** [comment]
OK, no way to trigger this from CLI then. I'll continue with the deactivate/activate route for now since this can be automated on CLI.

**Comment by PowerKiKi** [comment]
I'd welcome a solution to automate that, but I could not come up with any reliable solution.

**Comment by mbrodala** [comment]
Well, a simple solution could be providing a CLI command (e.g. via Extbase CommandController) for this.

**Comment by mbrodala** [comment]
Even better would probably be an integration into the upgrade wizards of the TYPO3 install tool. The TYPO3 Console already has specific commands for executing these via CLI.

**Comment by PowerKiKi** [comment]
If you can describe in more detail a standard and standalone way, that would be great. But AFAIK Extbase command would be non-standard (so hard to discover), and TYPO3 Console would be an undesired dependency. IMHO the failure lies with core which fails to provide the necessary hooks (or I am not aware of them).

**Comment by mbrodala** [comment]
Have a look at the TYPO3 upgrade wizards, they basically do this ([example](https://github.com/TYPO3/TYPO3.CMS/commit/6f7b5452f6d31d741e68fdf71e13a4768e2131fa)). They can be triggered visually through the Install Tool as usual or automatically thanks to the TYPO3 Console.

You don't have to add a dependency on the TYPO3 Console, but I'd expect that basically everyone working with TYPO3 on the CLi is using it anyways. ;-)

**Comment by PowerKiKi** [comment]
It's the first time I hear about wizards being used for extensions. Is [class.ext_update.php	
](https://docs.typo3.org/typo3cms/CoreApiReference/singlehtml/#reserved-filenames) deprecated ? do you have any link to other extension using wizards instead of traditional update way ?

It seems to me to be counter-intuitive to not use the system that was made specifically for extension update.

**Comment by mbrodala** [comment]
No, you can still use `ext_update` if you want but IMO the upgrade wizard system from the Install Tool offers a basic framework for updates/migrations which one otherwise needs to build manually.

The problem with `ext_update` from my POV is that one is free to do what he wants here, including showing interactive multi-step forms. Such kind of update scripts are basically impossible to invoke from CLI, the upgrade wizards don't suffer from this.

**Pull request closed without merging**
